server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: tacodb
    password: tacopassword
    schema:
      - order-schema.sql
      - ingredient-schema.sql
      - tao-schema.sql
      - user-schema.sql
    data:
      - ingredients.sql
taco:
  orders:
    pageSize: 10
